// <auto-generated />
using ConfigManagerStend.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfigManagerStend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.BuildDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameRepo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BuildDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameRepo = "Delo2020",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            NameRepo = "Delo2020-CB",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            NameRepo = "Delo2020-EEK",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            NameRepo = "Delo2020-GD",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            NameRepo = "Delo2020-Kaliningrad",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 6,
                            NameRepo = "Delo2020-MinKult",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 7,
                            NameRepo = "Delo2020-MinTrud",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 8,
                            NameRepo = "TITUL",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 9,
                            NameRepo = "Nadzor2025",
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.ConfigStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfigStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Подключен"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Отключен"
                        });
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.ConfigStend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Appn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxSettingDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathStend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformHostDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PortA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingDb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.ToTable("ConfigStends", (string)null);
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.ExternalModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateFileReplacement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFileVerifiedToExist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPathFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StandId");

                    b.HasIndex("StatusId");

                    b.ToTable("ExternalModules", (string)null);
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.Stand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppPort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChekedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DbOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DbProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SrvAFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stands", (string)null);
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.TeamProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameProject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamProjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameProject = "Delo2020"
                        },
                        new
                        {
                            Id = 2,
                            NameProject = "TITUL"
                        },
                        new
                        {
                            Id = 3,
                            NameProject = "Nadzor2025"
                        });
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.BuildDefinition", b =>
                {
                    b.HasOne("ConfigManagerStend.Domain.Entities.TeamProject", "TeamProject")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamProject");
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.ConfigStend", b =>
                {
                    b.HasOne("ConfigManagerStend.Domain.Entities.BuildDefinition", "BuildDefinition")
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildDefinition");
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.ExternalModule", b =>
                {
                    b.HasOne("ConfigManagerStend.Domain.Entities.Stand", "Stand")
                        .WithMany("Modules")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigManagerStend.Domain.Entities.ConfigStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stand");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ConfigManagerStend.Domain.Entities.Stand", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
